{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintSi where

-- pretty-printer generated by the BNF converter

import AbsSi
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Program where
  prt i e = case e of
   Prog stms -> prPrec i 0 (concatD [prt 0 stms])


instance Print Dec where
  prt i e = case e of
   DFunc type' id params stms -> prPrec i 1 (concatD [prt 0 type' , prt 0 id , doc (showString "(") , prt 0 params , doc (showString ")") , doc (showString "{") , prt 0 stms , doc (showString "}")])
   DVar type' id -> prPrec i 1 (concatD [prt 0 type' , prt 0 id])
   DInit type' id exp -> prPrec i 1 (concatD [prt 0 type' , prt 0 id , doc (showString "=") , prt 0 exp])
   DAuto id exp -> prPrec i 1 (concatD [doc (showString "auto") , prt 0 id , doc (showString "=") , prt 0 exp])
   DArr type' id exp -> prPrec i 1 (concatD [prt 0 type' , prt 0 id , doc (showString "[") , prt 0 exp , doc (showString "]")])
   DStruct id decs -> prPrec i 0 (concatD [doc (showString "struct") , prt 0 id , doc (showString "{") , prt 1 decs , doc (showString "}")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 1 x , doc (showString ";") , prt 1 xs])

instance Print Param where
  prt i e = case e of
   Param paramtype id -> prPrec i 0 (concatD [prt 0 paramtype , prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print ParamType where
  prt i e = case e of
   ParamTypeVal type' -> prPrec i 0 (concatD [prt 0 type'])
   ParamTypeRef type' -> prPrec i 0 (concatD [prt 0 type' , doc (showString "&")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Stm where
  prt i e = case e of
   SDec dec -> prPrec i 0 (concatD [prt 0 dec , doc (showString ";")])
   SExp exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])
   SBlock stms -> prPrec i 0 (concatD [doc (showString "{") , prt 0 stms , doc (showString "}")])
   SIf exp stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SIfElse exp stm0 stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm0 , doc (showString "else") , prt 0 stm])
   SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SFor dec exp0 exp stm -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 dec , doc (showString ";") , prt 0 exp0 , doc (showString ";") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SRet  -> prPrec i 0 (concatD [doc (showString "return") , doc (showString ";")])
   SRetExp exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])
   SPrint exp -> prPrec i 0 (concatD [doc (showString "print") , prt 0 exp , doc (showString ";")])
   SPrintLn exp -> prPrec i 0 (concatD [doc (showString "println") , prt 0 exp , doc (showString ";")])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Exp where
  prt i e = case e of
   EAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "=") , prt 0 exp])
   EIncL var -> prPrec i 0 (concatD [doc (showString "++") , prt 0 var])
   EIncR var -> prPrec i 0 (concatD [prt 0 var , doc (showString "++")])
   EDecL var -> prPrec i 0 (concatD [doc (showString "--") , prt 0 var])
   EDecR var -> prPrec i 0 (concatD [prt 0 var , doc (showString "--")])
   EAddAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "+=") , prt 0 exp])
   ESubAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "-=") , prt 0 exp])
   EMulAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "*=") , prt 0 exp])
   EDivAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "/=") , prt 0 exp])
   EModAss var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "%=") , prt 0 exp])
   ENot exp -> prPrec i 1 (concatD [doc (showString "~") , prt 1 exp])
   EAnd exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "&&") , prt 2 exp])
   EOr exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "||") , prt 2 exp])
   EEq exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString "==") , prt 3 exp])
   ENeq exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString "!=") , prt 3 exp])
   ELt exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString "<") , prt 3 exp])
   EElt exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString "<=") , prt 3 exp])
   EGt exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString ">") , prt 3 exp])
   EEgt exp0 exp -> prPrec i 2 (concatD [prt 3 exp0 , doc (showString ">=") , prt 3 exp])
   EConc exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "**") , prt 4 exp])
   EAdd exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "+") , prt 5 exp])
   ESub exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "-") , prt 5 exp])
   EMul exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "*") , prt 6 exp])
   EDiv exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "/") , prt 6 exp])
   EMod exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "%") , prt 6 exp])
   EInt n -> prPrec i 6 (concatD [prt 0 n])
   ETrue  -> prPrec i 6 (concatD [doc (showString "true")])
   EFalse  -> prPrec i 6 (concatD [doc (showString "false")])
   EChar c -> prPrec i 6 (concatD [prt 0 c])
   EStr str -> prPrec i 6 (concatD [prt 0 str])
   EVar var -> prPrec i 6 (concatD [prt 0 var])
   ECall var exps -> prPrec i 6 (concatD [prt 0 var , doc (showString "(") , prt 0 exps , doc (showString ")")])
   EFunc type' params stms -> prPrec i 6 (concatD [doc (showString "(") , prt 0 type' , doc (showString ";") , prt 0 params , doc (showString ")") , doc (showString "{") , prt 0 stms , doc (showString "}")])
   EArr exps -> prPrec i 6 (concatD [doc (showString "{") , prt 0 exps , doc (showString "}")])
   EIntToChar exp -> prPrec i 6 (concatD [doc (showString "(char)") , prt 0 exp])
   ECharToInt exp -> prPrec i 6 (concatD [doc (showString "(int)") , prt 0 exp])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Type where
  prt i e = case e of
   TInt  -> prPrec i 0 (concatD [doc (showString "int")])
   TBool  -> prPrec i 0 (concatD [doc (showString "bool")])
   TChar  -> prPrec i 0 (concatD [doc (showString "char")])
   TString  -> prPrec i 0 (concatD [doc (showString "string")])
   TVoid  -> prPrec i 0 (concatD [doc (showString "void")])
   TArr type' -> prPrec i 0 (concatD [prt 0 type' , doc (showString "[]")])
   TStruct id -> prPrec i 0 (concatD [doc (showString "struct") , prt 0 id])
   TFunc type' paramtypes -> prPrec i 0 (concatD [doc (showString "(") , prt 0 type' , doc (showString ";") , prt 0 paramtypes , doc (showString ")")])


instance Print Var where
  prt i e = case e of
   VarArr var exp -> prPrec i 0 (concatD [prt 0 var , doc (showString "[") , prt 0 exp , doc (showString "]")])
   VarStruct var id -> prPrec i 1 (concatD [prt 0 var , doc (showString ".") , prt 0 id])
   VarIdent id -> prPrec i 2 (concatD [prt 0 id])



